Project 5 - Cluedo - Emmie Nilsson
Technigo/project-cluedo pull request #10
Opened 2019-10-25 18:42 UTC by eilsson

- Changed my room array to an object with more information instead.
- Made the site responsive.
- Styled the site.
- Added images for all the cards.
- Added the functionality to the reveal button. 

I only looked at the site in Google Chrome while I was coding. When I deployed my site on netlify I noticed that a lot of browsers aren't handling the transforms very well. For my next project I'll look at the site in other browsers while I'm coding it.

2019-10-29 18:27 UTC, ericaglimsholt requested changes
Please provide a Netlify link to your PR!

2019-11-03 16:09 UTC, eilsson commented
I have updated my pull request with the url to my project.
https://project5-cluedo-emmie.netlify.com/

2019-11-04 16:52 UTC, ericaglimsholt approved these changes
Great work!
I think your design is nice and clean, and so are your code. It was really nice going through the code - it was easy for me to understand what you have done. Keep it going!

2019-11-04 16:52 UTC, ericaglimsholt commented on code/index.html
> +    <h1 id="mystery" class="mystery-title"></h1>
This looks like it will suit better as a `<h2>` element because you already have a `<h1>` that describes the page

2019-11-04 16:52 UTC, ericaglimsholt commented on code/style.css
> +}
Good that you collide these parts!

2019-11-04 16:52 UTC, ericaglimsholt commented on code/style.css
> +  perspective: 1000px;
Hm, are you using this in some way?

2019-11-04 16:52 UTC, ericaglimsholt commented on code/clue.js
> +console.log(rooms);
Delete log

2020-09-14 07:41 UTC, closed without merging