Cluedo
Technigo/project-cluedo pull request #102
Opened 2020-09-18 13:06 UTC by carolinebirgersson

Here is my Cluedo page!

2020-09-25 16:26 UTC, ssundblom requested changes
Good job Caroline! I think you've done a great game and I really love the styling and all the details you put in to it 😍
Now I just think you need to get the 'crime solution' button to work and you are good to go! Celebrate your progress! 🥳

***change request***
- You should be able to reveal the mystery.

2020-09-25 16:26 UTC, ssundblom commented on code/clue.js
> +  }
Really like the comments you left here :)

2020-09-25 16:26 UTC, ssundblom commented on code/clue.js
> +  //I would have added objects for all of the rooms if I had the time.
Here as well!

2020-09-25 16:26 UTC, ssundblom commented on code/clue.js
>  // CREATE AN OBJECT THAT KEEPS THE MYSTERY.
Maybe remove the comments from the assignment? Makes it a bit easier to read :)

2020-09-25 16:26 UTC, ssundblom commented on code/clue.js
> +revealMystery()
I think this is why the scarlet picture, the library image and axe always is revealed when clicking 'crime solution'. It's hard coded to be these specific pictures. Could it be better to give the 'solutionText' something like ${mystery.killer.firstName}, ${mystery.killer.lastName},  ${mystery.weapon} and so on?

2020-09-25 16:26 UTC, ssundblom commented on code/clue.js
> +
love your functions! Very nice and easy to read!

2020-09-25 16:26 UTC, ssundblom commented on code/index.html
> +      <div class='solution'>
Here I see you've used onclick and in the JS code I saw you used addEventListener! Super that you master and understand both of them :) 😍 Maybe nest time choose one of them for a more unified code ☺️

2020-09-25 16:26 UTC, ssundblom commented on code/style.css
> +
The styling 😍 
I love the color theme and the newspaper background - very murder mysterious!

2020-09-25 16:26 UTC, ssundblom commented on code/style.css
> +  background: white;
I don't think you need to repeat the font-family in the classes when you have them in the body.  Makes a little less work 👍

2020-09-25 16:26 UTC, ssundblom commented on code/style.css
The hover effect is so nice! Love that detail 👌

2020-09-25 16:26 UTC, ssundblom commented on code/style.css
> +
The hover here as well! :)

2020-09-28 11:44 UTC, EmOlsz requested changes
Hi Caroline! I would like to congratulate you on effort you put into this project, but unfortunately there are a lot of bugs in your code...
I got impression that you haven't checked your code before submitting it. I would love if you could analyse it step by step (at least JS file) and deduct what's wrong with it. Hope my comments will help you with that :)
I will need to see changes before I will be able to approve it.

Let me point out what should be fixed :
1. You initialise your project in wrong way, adding new properties later on. Please, check out my comments in code regarding that
2. You use `event` object and default function parameters wrong way
3. Your solution is hardcoded, so we always reveal mystery with the same person, weapon and room
4. I've got impression that you don't understand some of style you use. Please, if you don't know what they are doing, learn about them or delete them

2020-09-28 11:44 UTC, EmOlsz commented on code/clue.js
> +  rooms:[]
Why do you initialise your mystery object with arrays of all suspects, weapons and empty array of rooms?
At the beginning it should be empty, and later on you should add to each property (so, suspect, weapon and rooms (please, notice that these are single, not multi)) value as single element from suspets, weapons and rooms array. So

1. Beginning :
```
const mystery = {
  suspect: null,
  weapon: null,
  rooms: null
}
```

2. Finish :
```
mystery = {
  suspect: //Mr green object,
  weapon: // knife object,
  rooms: // dining room object
}
```

2020-09-28 11:44 UTC, EmOlsz commented on code/clue.js
>    mystery.killer = randomSelector(suspects)
So, `suspect` or a `killer`? You haven't initialised your object with property called `killer` so after this line your mystery object has 4 properties : suspects, weapons, rooms and killer. That doesn't make sense

2020-09-28 11:44 UTC, EmOlsz commented on code/clue.js
> +  mystery.weapon = randomSelector(weapons)
Another new property added to mystery object, right now we have 5 of them : suspects, weapons, rooms, killer and weapon

2020-09-28 11:44 UTC, EmOlsz commented on code/clue.js
> +  mystery.room = randomSelector(rooms)
6 of them right now

2020-09-28 11:44 UTC, EmOlsz commented on code/clue.js
> +  event.preventDefault();
`event` is no variable or some sort of that. It's an argument passed to your function that you need to provide. In your code, you called it `mystery`, so you should write `mystery.preventDefault()`

2020-09-28 11:44 UTC, EmOlsz commented on code/clue.js
> +revealMystery()
Yep, it should be done like this

2020-09-28 11:44 UTC, EmOlsz commented on code/index.html
> +    <link rel='stylesheet' href='style.css' />
Let's not forget about `./` in path to file

2020-09-28 11:44 UTC, EmOlsz commented on code/index.html
> +        <img id='killerImage' src='' height='75%' />
We should avoid setting style properties via HTML - all of them should be added in CSS files

2020-09-28 11:44 UTC, EmOlsz commented on code/index.html
> +    <script src='clue.js'></script>
`./`

2020-09-28 11:44 UTC, EmOlsz commented on code/style.css
> +  background: white;
Good point Sara!

2020-09-28 11:44 UTC, EmOlsz commented on code/style.css
> +#weaponName, #killerName, #roomName {
We should avoid styling by id's, use classes instead

2020-09-28 11:44 UTC, EmOlsz commented on code/style.css
>  .weapon-deck {
There is a lot of shared styles between killer-deck, weapon-deck and room-deck - They could be unified to one class, and have separate classes only for styles that are not shared between them

2020-09-28 11:44 UTC, EmOlsz commented on code/style.css
> +  content: '';
What do you use `content` property for? This property is used only for `after` and `before` elements, it doesn't have any impact on styles over here

2020-09-28 11:44 UTC, EmOlsz commented on code/clue.js
> +    ).addEventListener('click', pickKiller);
Very nice :)

2020-10-13 12:08 UTC, EmOlsz approved these changes

2021-03-11 09:11 UTC, closed without merging