Cluedo - Nathalie
Technigo/project-cluedo pull request #104
Opened 2020-09-18 13:23 UTC by nathalienordstrom

2020-09-22 11:27 UTC, ckjerrgren reviewed
Very nice website! 

I like all the little extra effects you've added and that it is responsive. 
Very readable code but you could have added your own comments to make it even easier for others to read and understand.

2020-09-22 11:27 UTC, ckjerrgren commented on code/clue.js
>  }
I think that if you had used the function that was suggested by the teachers 
```
  document.getElementById( 'killerName').innerHTML =`${mystery.killer.firstName}${mystery.killer.lastName}`
```
you could have gotten away with writing less code. Don't know if it was necessary to set the variables(objects?) as const first.

2020-09-22 11:27 UTC, ckjerrgren commented on code/clue.js
>  }
Same with weapon and room :)

2020-09-22 11:27 UTC, ckjerrgren commented on code/clue.js
> +const revealMystery = () => {
Nice use of if and else from last week

2020-09-22 11:27 UTC, ckjerrgren commented on code/index.html
> +  <link rel="shortcut icon" type="image/png" href="favi.png">
I like the favicon

2020-09-22 11:27 UTC, ckjerrgren commented on code/style.css
> +button:hover {
Wow!

2020-09-22 11:27 UTC, ckjerrgren commented on code/style.css
> +.weapon-deck img {
Some of the weapon pictures takes a bit longer to load than the rest.
Are some of them larger?

2020-09-23 12:26 UTC, nathalienordstrom commented on README.md
> +https://app.netlify.com/sites/cluedo-nathalie/settings/general.
https://cluedo-nathalie.netlify.app

2020-09-25 11:29 UTC, EmOlsz requested changes
Good job Nathalie, congratulations on well done project :)
I would like you to check out both Claudia's and my comment and fix your code accordingly to them. After that, project will be approved!

2020-09-25 11:29 UTC, EmOlsz commented on code/clue.js
> +
Unnecessary blank line

2020-09-25 11:29 UTC, EmOlsz commented on code/clue.js
> +
It's far more clean to initialise our `mystery` object already with properties that are going to be there at the end, but with initial value of `null`, like that :
```
const mystery = {
  killer: null,
  weapon: null,
  room: null,
}
```

2020-09-25 11:29 UTC, EmOlsz commented on code/clue.js
> +const theKillerAge = document.getElementById("killerAge")
Wrong indentation everywhere in this function

2020-09-25 11:29 UTC, EmOlsz commented on code/clue.js
> +const theWeapon = document.getElementById("weapon")
We don't need prefix `the` in every variable - let's delete that

2020-09-25 11:29 UTC, EmOlsz commented on code/style.css
> +  background-image: url(assets/cluedo_cover.jpeg);
Let's wrap it up with quote marks, like that :
```
background-image: url("assets/cluedo_cover.jpeg");
```
Some browsers might not approve this value without quote marks

2020-09-25 11:29 UTC, EmOlsz commented on code/style.css
> +#killer.killer-deck {
We should avoid styling by ids, let's change that to class reference

2020-09-25 11:29 UTC, EmOlsz commented on code/style.css
> +  margin-bottom:0px;
No need to add `px` when value is equal `0`. `margin-bottom: 0;` is completely ok

2020-09-25 11:29 UTC, EmOlsz commented on code/style.css
> +
unnecessary blank lines

2020-09-25 13:39 UTC, nathalienordstrom commented
a

2020-11-27 10:04 UTC, nathalienordstrom commented
Have I not fixed all that you wanted or what's left?

2020-11-27 10:06 UTC, EmOlsz commented
I might have missed some notifications about your changes, sorry.
Project is approved :)

2020-11-27 10:06 UTC, EmOlsz approved these changes

2021-03-11 09:11 UTC, closed without merging