Project 4- Cluedo Jessica Panditha
Technigo/project-cluedo pull request #111
Opened 2020-09-18 16:26 UTC by jespa374

I did the blue level and some red level points.  In general I am happy about the way it turned out. I do think that the images are sometimes displayed a bit slowly (the weapon images and the room images) and I don't know how to fix that.

https://cluedomurdermystery.netlify.app/

2020-09-23 15:31 UTC, MindstormingAB requested changes
Well done Jessica! You did a great job with this week's project. It looks nice and works as intended.
I loved the Cluedo text, the hover effects and the gradient backgrounds. 👏🏻

You understand JavaScript concepts and can use them to achieve blue and red levels. In the upcoming projects, you should stretch to "simplify" your JS flow by creating global variables and use them in your functions. 

I'd like you to make some minor changes to follow the code guidelines and the project brief:
- Remove console.logs
- Remove commented code
- Increase animation time with 1 sec

If you have time, try to resize your images using https://resizeimage.net/ in order to improve your web page load time.

Keep up the good work! 💪

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +  setTimeout(pickKiller, 1000);
According to the brief, the loading animations should last a couple of seconds. 1000 in your function means 1 second, maybe you could increase to 2000 to be on the safe side 😉

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +  }
Well done with this red level goal 💯

2020-09-23 15:31 UTC, MindstormingAB commented on README.md
> +I started creating objects for each catergory and arrays with the objects created. Then I did the functions so that each time you click the card the different properties of random objects would displ
Good description!

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +  description: 'pale, morbid, stoic',
I love your descriptions 😁

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +console.log(msScarlett.firstName);
console.logs are awesome in development but not to be left behind 😇

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +console.log(rooms[rooms.length-1]);
More console.logs 😜

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +    document.getElementById('killerAge').innerHTML=mystery.killer.age;
You are using a lot of document.getElementById inside your functions, which makes your code longer and a bit difficult to read. You could simplify your functions by creating a set of constants, between your arrays and your functions (starting row 267).
It could look like:
```
const loaderKiller =  document.getElementById('loaderKiller');
const killerCard = document.getElementById('killerCard');
const killerImage = document.getElementById('killerImage');
const killerDescription = document.getElementById('killerDescription');
const killerOccupation =  document.getElementById('killerOccupation');
const killerAge = document.getElementById('killerAge');
```
and so on...
Later on, in your code, you can use these constants to shorten the code:
```
const pickKiller = () => {
  loaderKiller.style.display = 'none';
  mystery.killer = randomSelector(suspects);
  killerCard.style.background = mystery.killer.color;
  killerName.innerHTML = `${mystery.killer.firstName} ${mystery.killer.lastName}`;
  killerImage.src = mystery.killer.image;
  killerDescription.innerHTML = mystery.killer.description;
  killerOccupation.innerHTML = mystery.killer.occupation;
  killerAge.innerHTML = mystery.killer.age;
}
```

2020-09-23 15:31 UTC, MindstormingAB commented on code/index.html
> +        <h1 class="heading">CL<span class="headingu">U</span>EDO</h1>
Cool! 👌

2020-09-23 15:31 UTC, MindstormingAB commented on code/index.html
> +    <button id="reveal" onclick="revealMystery()">REVEAL THE CRIME</button>
Since we have a js.file, I would have moved this action to the .js file, for consistency.
html:
`<button id="reveal">REVEAL THE CRIME</button>`
javascript:
```
const revealButton = document.getElementById('reveal');
revealButton.onclick = revealMystery;
```

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +
I would have called the revealMystery function from clue.js, not from index.html.
```
const revealButton = document.getElementById('reveal');
revealButton.onclick = revealMystery;
```

2020-09-23 15:31 UTC, MindstormingAB commented on code/style.css
> +#loaderKiller, #loaderWeapon, #loaderRoom {
We shouldn't style by id's, it's always better to add class to elements as well and reference to the class in CSS.
In your case, you could add `name="loader"` to your loader placeholders in index.html and use .loader here in style.css

2020-09-23 15:31 UTC, MindstormingAB commented on code/style.css
> +  background: linear-gradient(90deg, rgba(6,6,20,0) 0%, rgba(44,58,121,0.12837009803921573) 0%, rgba(28,41,18,1) 0%, rgba(22,29,47,0.9266894257703081) 100%, rgba(0,212,255,1) 100%);
Nice gradient backgrounds 👌

2020-09-23 15:31 UTC, MindstormingAB commented on code/style.css
> +  100% { transform: rotate(360deg); }
👏 Red level! 👏

2020-09-23 15:31 UTC, MindstormingAB commented on code/style.css
> +  transform: scale(1.5);
Like it! 😍

2020-09-23 15:31 UTC, MindstormingAB commented on code/index.html
> +        <img id="roomImage" src="" height="100" />
You spent time on choosing nice pictures, I think you should adjust their height so they get bigger, there is more space on the card. 
Furthermore, I noticed that your images were huge. I think that it is the reason why they are loading so slowly on your web page. Maybe you could use a tool as https://resizeimage.net/ and reduce them?

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +  //document.getElementById('killerCard').onclick = pickKiller;
Don't forget to remove commented code before pushing.

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +//document.getElementById('weaponCard').onclick = pickWeapon;
Don't forget to remove commented code before pushing.

2020-09-23 15:31 UTC, MindstormingAB commented on code/clue.js
> +//document.getElementById('roomCard').onclick = pickRoom;
Don't forget to remove commented code before pushing.

2020-09-28 17:23 UTC, EmOlsz requested changes
Good job Jessica! I really like that you've done more than blue requirements :) Keep up the good work, I'm happy to see this progress!
Even though, before I will be able to approve your project, I need to see some changes from comments. Please, take a look on them and provide changes :)

2020-09-28 17:23 UTC, EmOlsz commented on code/clue.js
> +patio
Wrong indentation

2020-09-28 17:23 UTC, EmOlsz commented on code/clue.js
> +  room: null
Very nice you initialised mystery object with null values! That's the cleanest approach :)

2020-09-28 17:23 UTC, EmOlsz commented on code/clue.js
> +    const shuffleFavouriteWeapon = () => {
Wrong indentation

2020-09-28 17:23 UTC, EmOlsz commented on code/index.html
> +        <h1 class="heading">CL<span class="headingu">U</span>EDO</h1>
Yes, very nice :)

2020-09-28 17:23 UTC, EmOlsz commented on code/style.css
> +  transform: scale(1.01);
👍

2020-10-04 20:54 UTC, EmOlsz approved these changes

2021-03-11 09:11 UTC, closed without merging