Cluedo - Evelina
Technigo/project-cluedo pull request #117
Opened 2020-09-19 17:19 UTC by evelinabe

Link to my deployed project:
https://evelinabe-cluedo.netlify.app/ 

My reflections on how this week's project turned out:
I'm super happy with the flickering letter. Spent a little too much time trying to merge my loader functions before asking for help.  Would still like a more simple and general version of the function - I'm guessing there's one out there, but anyhow - it w o r k s.

Couldn't get loader item over each element to work, so went for one over the whole page instad. Tried to insert text but it did not show. If I had had more time I would have tried to figure it out. 

Perhaps I spent a little too much time on the styling, but it also helped me to get a clearer view of what I wanted to happen on the page.

2020-09-23 08:23 UTC, AnnaHellqvist approved these changes
Great job Evelina, I am really impressed. I read that you had some trouble to make the loader appear for the separate cards. I don't know what approaches you have tried but I had to do three separate functions for this to work, that I call before the pick functions. Don't know if this could work for you, there is probably a smarter way to do it than I did also :)

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/clue.js
> +  image: "assets/mr_green.jpg",
missing the "./" in ./assets/mr_green.jpg. Check some of the other suspects objects as well : )

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/index.html
> +        <h1 class="title">CL<span id="flickering-letter">U</span>EDO</h1>
Why Id used for styling?

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/clue.js
> +shuffleFavoriteWeapon = (suspects) => {
I like your solution for shuffling favorite weapon, looks clean! re-using the randomSelector function, nice 🥇

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/index.html
> +    <div class="loader-container">
Great job on naming your classes, the HTML is easy to follow and understand what the elements are for 👍

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/clue.js
> +    loader.classList.toggle("is-active");
Since I havent had the time to familiarize a lot with classList and toogle I would have liked a comment with an explanation of whats happening in these functions :)

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/clue.js
> +// -----------------GENERAL VARIABLES-----------
The general variables really makes the code cleaner further down 💯 👍

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/clue.js
> +document.getElementById("roomCard").addEventListener("click", showCard);
Consistency in using semicolon and "" throughout the code, great job! 🥇

2020-09-23 08:23 UTC, AnnaHellqvist commented on code/clue.js
> +};
Creating objects for the different cards, nice approach :D again, really made the code cleaner for me to read!

2020-09-23 15:31 UTC, evelinabe commented on code/clue.js
> +  image: "assets/mr_green.jpg",
Thank you, will fix that!

2020-09-24 13:44 UTC, evelinabe commented on code/index.html
> +        <h1 class="title">CL<span id="flickering-letter">U</span>EDO</h1>
- [ ] Changed to class

2020-10-01 19:09 UTC, EmOlsz requested changes
Congratulations for your project Evelina! You've done many things in your code by clean way, I'm happy to see that :) On the other hand, some things could be improved - please, take a look on comments provided with code review and fix what needs to be fixed. After that, I'll be able to approve your project :)

2020-10-01 19:09 UTC, EmOlsz commented on code/clue.js
> +const randomSelector = array => array[Math.floor(Math.random() * array.length)];
super!

2020-10-01 19:09 UTC, EmOlsz commented on code/clue.js
> +  return suspects.map(suspect => {
It shouldn't be `.map()` method and you shouldn't return anything, because you never use this returned value.
Far cleaner way of writing this would be with `.forEach()` and without `return`

2020-10-01 19:09 UTC, EmOlsz commented on code/clue.js
> +      return true;
Very nice, clean function :)

2020-10-01 19:09 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="./style.css" />
:)

2020-10-01 19:09 UTC, EmOlsz commented on code/style.css
> +  right: 0;
The order should always be : top, right, bottom, left (so, clockwise)

2020-10-01 19:09 UTC, EmOlsz commented on code/style.css
> +  box-shadow: #c8d5db 1px 1px 10px;
Wrong order of values - this shouldn't work.
Proper one would be `box-shadow: 1px 1px 10px #c8d5db;`

2020-10-07 08:53 UTC, evelinabe commented
Thank you, Maks. Have pushed the required changes.

2020-10-11 12:04 UTC, evelinabe commented on code/style.css
> +  right: 0;
This is changed, but for some reason does not show up as outdated here.

2020-10-13 09:00 UTC, EmOlsz approved these changes

2021-03-11 09:11 UTC, closed without merging