Cluedo - Mystery Randomizer by Ylva
Technigo/project-cluedo pull request #118
Opened 2020-09-19 18:24 UTC by ylvan75

I'm aware of thing if I have  two or more attributes I should add linebreaks to increase readability.

I use Prettier (with default settings) and when I do save it change it back to be on one single line.

For next weeks project I will look into that and see what I need to change in Prettier to be able to add linebreaks.

Happy to get advice what I have to do.

2020-09-22 18:58 UTC, sarahejhej requested changes
Well done on this project! Your README.md was very informative and explanatory, and your comment about the formatting in the pull request made it easier to look through the code. 
I know that you feel like you struggle with the design, but I think both the design and the layout are very clean! And I like the colour scheme. The page is also responsive, which is great. It wasn't part of the assignment, but you made the extra effort to do so. And also, it's mobile first 👍

When testing your site I noticed that you made sure that you could't reveal the mystery before all cards were picked. I think that you easily could have added an if-statement in your pick functions to check if the cards were picked in the right order. You already had all the variables set up to do so!

Your HTML and CSS files was very clean and organised and follow a structured order. All the class names made sense, the HTML tags were semantic. Indentation looks good. Maybe you could add header comments to to group classes/HTML tags together. 

In the JavaScript file there were a few `console.log()` to remove. I think you could also remove some of the instructions, old comments and blank lines to make the code even cleaner. That's all to be done before being approved! 😄
```

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +console.log(knife.weight);
Remember to delete all `console.log` before pull request!

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
>  // NOW GROUP ALL SUSPECTS, WEAPONS AND ROOMS IN ARRAYS LIKE THIS:
I think the code would be cleaner if instructions like these were deleted. Maybe adding own comment headers to make it easier to navigate in the code? Like variables and functions etc

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +];
Some rooms occur more than once. Is that to make them more likely to be picked?

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +  event.preventDefault();
This was new to me, `event.preventDefault()`, have to look into it!

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +      ).innerHTML = `Favourite Weapon: ${mystery.killer.favouriteWeapon}`;
I get the same formatting, it makes it so hard to read! If you find out how to change it please let me know

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +      // This will change the background color of the card to the one connected to the chosen killer and show the full name of the killer. Feel free to add more things to show about the killer.
I think you can delete a few blank lines here, I find it difficult to follow the code with the blank lines inside of a function

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +    killerPicked = true;
This I recognise :)

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +      // This will change the card to the one connected to the chosen room and show which room it is.
Nice commenting! Makes it so much easier to follow the code!

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +    mystery.room === null
Always good to see solutions that differ from your own, great way to learn!

2020-09-22 18:58 UTC, sarahejhej commented on code/clue.js
> +document.getElementById("revealCard").addEventListener("click", revealMystery);
This looks super clean! I struggled to understand the syntax of `.addEventListener`

2020-09-22 18:58 UTC, sarahejhej commented on code/index.html
> +    <meta name="author" content="Ylva Nilsson" />
Never seen this, cool!

2020-09-22 18:58 UTC, sarahejhej commented on code/index.html
> +    <link rel="icon" type="image/png" sizes="16x16" href="./assets/loupe.png" />
I like the icon!

2020-09-22 18:58 UTC, sarahejhej commented on code/style.css
>    width: 90%;
Great with mobile first!

2020-09-22 18:58 UTC, sarahejhej commented on code/style.css
> +@keyframes heartbeat {
I like the animation!

2020-09-22 18:58 UTC, sarahejhej commented on code/style.css
> +@media (min-width: 481px) {
This is so clean - having to add just a few lines to make the site responsive. Yay!

2020-09-22 18:58 UTC, sarahejhej commented on code/style.css
> +@media (min-width: 481px) {
The first breakpoint is usually at 768 px

2020-09-22 18:58 UTC, sarahejhej commented on code/index.html
> +        <img id="killerImage" src="" height="200" />
I think the height attribute could be moved into the style.css file

2020-09-24 11:29 UTC, ylvan75 commented on code/clue.js
> +console.log(knife.weight);
I have deleted this and other console.log that I had in the file.

2020-09-24 11:30 UTC, ylvan75 commented on code/clue.js
>  // NOW GROUP ALL SUSPECTS, WEAPONS AND ROOMS IN ARRAYS LIKE THIS:
Removed unnecessary instructions and made sure I have my own comments, I hope it's much cleaner now.

2020-09-24 11:31 UTC, ylvan75 commented on code/clue.js
> +];
It was a mistake from from me, now fixed. Thanks for the observation.

2020-09-24 13:33 UTC, sarahejhej approved these changes

2020-10-06 10:18 UTC, EmOlsz approved these changes
Good job Ylva, congratulations on this project :) You made extra requirements and they work well!
Take a look at my comments, I hope they will help you improve even more :)

2020-10-06 10:18 UTC, EmOlsz commented on code/clue.js
> +let roomPicked = false;
Good idea :)

2020-10-06 10:18 UTC, EmOlsz commented on code/clue.js
> +const randomSelector = (array) => {
No need for set of parentheses if you pass only one argument :

```
const randomSelector = array => { ... }
```

2020-10-06 10:18 UTC, EmOlsz commented on code/clue.js
> +  weapon: null,
Great job again, it's the best option to initialise object with `null` values if you want to overwrite them later on :)

2020-10-06 10:18 UTC, EmOlsz commented on code/clue.js
> +    cleanRevealMysteryMessage(); // Removes "Reveal the crime" message if any
👍

2020-10-06 10:18 UTC, EmOlsz commented on code/clue.js
> +    mystery.room === null
You can simplify it :

```
  if (!mystery.killer || !mystery.weapon || !mystery.room) { ... }
```

for more information, check out https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/

2020-10-06 10:18 UTC, EmOlsz commented on code/index.html
>      <link rel="stylesheet" href="style.css" />
`./` missing in path to file

2020-10-06 10:18 UTC, EmOlsz commented on code/index.html
>      <script src="clue.js"></script>
`./`

2021-03-11 09:11 UTC, closed without merging