Handing in the project for week 5
Technigo/project-cluedo pull request #129
Opened 2020-09-20 12:32 UTC by HenrikeW

2020-09-21 16:16 UTC, karanmann approved these changes
Wow Henrike, This code was so clean and very understandable. Its great that you achieved the black level and should be very proud of it :) It was such a pleasure to read your code.

2020-09-21 16:16 UTC, karanmann commented on code/clue.js
>    return array[Math.floor(Math.random() * array.length)]
Missed lines with ;

2020-09-21 16:16 UTC, karanmann commented on code/clue.js
> +    weapons.push(weapon, weapon, weapon, weapon)
I guess it will missed here too :)

2020-09-21 16:16 UTC, karanmann commented on code/clue.js
> +const revealMystery = () => {
Love how you validated that the cards were picked.

2020-09-21 16:16 UTC, karanmann commented on code/index.html
> +      <div class="footer-left">
This is so good. I need to make sure to reference too :)

2020-09-21 16:16 UTC, karanmann commented on code/style.css
> +@-webkit-keyframes spin {
The Animations really worked well.

2020-09-21 16:16 UTC, karanmann commented on code/style.css
> +
Its great that you made it responsive :)

2020-10-02 11:54 UTC, EmOlsz requested changes
Fantastic job Henrike - this is fine piece of application. You've done all basic and extra requirements this week :)
Nonetheless, some small detail-stuff have to be fixed, please take a look on both Karan's and my comments and implement changes. Only after that I'll be able to approve your project

2020-10-02 11:54 UTC, EmOlsz commented on code/clue.js
> +document.getElementById('roomCard').classList.add("active");
Since you add these classes at the very beginning without any user trigger, they should be just written in HTML

2020-10-02 11:54 UTC, EmOlsz commented on code/clue.js
> +  room: null
Very good value initialisation :) `null` is the most proper value here

2020-10-02 11:54 UTC, EmOlsz commented on code/clue.js
> +const shuffleFavouriteWeapon = person => person.favouriteWeapon = randomSelector(weapons).id;
Very good

2020-10-02 11:54 UTC, EmOlsz commented on code/clue.js
> +    mystery.weapon.favouriteRoom,
Well thought process

2020-10-02 11:54 UTC, EmOlsz commented on code/clue.js
> +  if (mystery.killer !== null && mystery.weapon !== null && mystery.room !== null) {
Or we could simplify this statement like this :

```
if (mystery.killer && mystery.weapon && mystery.room) { ... }
```

or eventually 

```
if (!!mystery.killer && !!mystery.weapon && !!mystery.room) { ... }
```

For further informations please check https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/

2020-10-02 11:54 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="style.css" href='https://fonts.googleapis.com/css?family=Girassol'/>
Missing `./` in path to file

2020-10-02 11:54 UTC, EmOlsz commented on code/index.html
>      <script src="clue.js"></script>
`./`

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +  background-image: url(./castleroom.jpg);
It's far more safe approach to wrap path in parentheses. Without them, some browsers might not find the path
`background-image: url("./castleroom.jpg");`

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +  font-family: Girassol;
Let's not forget about font-fallback : without it, if there would be any problems with accessing Girassol font, browser would display everything in nasty, basic font.

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +  padding: 50px 0px 200px 0px;
`padding : 50px 0 200px 0;`

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +  margin: 0px auto;
`margin: 0 auto;`

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +  padding: 50px 0px;
`padding: 50px 0;`

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +  top: 250px;
Semantic order of this properties should always be 1. top, 2. right, 3. bottom, 4. left - basically, clockwise

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +width: 125px;
wrong indentation

2020-10-02 11:54 UTC, EmOlsz commented on code/style.css
> +    margin: 0 20px 0 20px;
`margin: 0 20px;`

2020-10-16 15:02 UTC, HenrikeW commented
Now, I've fixed everzthing that you two commented on. Please approve my pull request :)

2020-10-17 09:39 UTC, EmOlsz approved these changes

2021-03-11 09:10 UTC, closed without merging