Clara Gyökeres Cluedo
Technigo/project-cluedo pull request #13
Opened 2019-10-26 13:15 UTC by claragyokeres

Here's my pull request!

2019-10-29 18:52 UTC, ericaglimsholt requested changes
Please add a Netlify link to your PR!

2019-10-29 18:54 UTC, claragyokeres commented
https://clarascluedo.netlify.com

2019-10-31 08:14 UTC, ericaglimsholt approved these changes
Hey Clara! Great work with your Cluedo assignment. What you can try to take with you for the next assignment is error handling. So if something doesn't work like it suppost to we need to handle that in some way. Usually we say to the user that this behavoir is wrong and a description how the user should do it. In this example an `alert` saying `you need to choose a room, killer and weapon to generate a murder` would do

2019-10-31 08:14 UTC, ericaglimsholt commented on code/clue.js
> +    (`The murder was committed by ${mystery.killer.firstName} ${mystery.killer.lastName}, in the ${mystery.room} with a ${mystery.weapon.name}.`)
Here you got an error when you are clicking on the button, but hasn't chosen a room, killer and weapon. For handling this you can do an if statement here. For example you can check if `mystery.killer.firstName` exists

2019-10-31 08:14 UTC, ericaglimsholt commented on code/clue.js
> +console.log(pickRoom);
```suggestion
console.log(pickRoom());
```

2020-09-14 07:41 UTC, closed without merging