Project 5 - Sara Stjernberg
Technigo/project-cluedo pull request #134
Opened 2020-09-20 14:38 UTC by stjernberg

I didn't have time manage to make the site responsive, since I found it very hard to make the flip cards look good in different screensizes. Would love to get feedback on how to do that. I didn't manage to get the flipcards to work properly in Firefox. Tried the -webkit- thing but it didn't work.

2020-09-21 14:11 UTC, Gabbi-89 approved these changes
Nice design and I really liked how you succeeded with flipping the cards. You have got everything to work out as it should when clicking the cards and when clicking on the button for revealing of the mystery. 
I really like the feature you added when all cards weren't clicked yet; "The murder can't be resolved yet."

The indents were done nicely through all the files! 

Don't forget to check your semicolons! You do use semicolons a lot but not everywhere. - eg.  after the functions they are missed. Use it nowhere or everywhere! 

Regarding the issues making it responsive I just have some few recommendations:
- Align the three cards to the center of the webpage - that makes them follow the centered alignment when minimizing the window.
- You can also set the width of the decks to 'auto'. 
- In my own project I added some margins for the tablet och mobile format which make the decks not float together.

Keep up the good work - you are great!

2020-09-21 14:11 UTC, Gabbi-89 commented on README.md
> +https://cluedo-myster-picker.netlify.app/
Really nice to see your cool webpage!
I would have liked some further descriptions in the Read me - section. I would like to understand how you faced the problems, did you meet any problems, which tools and techniques did you use, etc.
PS. Do not forget to check your spelling mistakes. ;)

2020-09-21 14:11 UTC, Gabbi-89 commented on code/index.html
> +    <header class="header">
Easy to follow the logic in your HTML file. You are using logical namings on the classes and the id's, which I easily can connect to what I see on the live webpage.

2020-09-21 14:11 UTC, Gabbi-89 commented on code/index.html
> +        </Section>
Now I am into details, put I would recommend you the change the 'S' to a small 's'.

2020-09-21 14:11 UTC, Gabbi-89 commented on code/style.css
> +
I do really see that you put a lot of effort to get the flip-cards to work nicely. Good work :)

2020-09-21 14:11 UTC, Gabbi-89 commented on code/style.css
> +    }
Maybe you could have commented the flip-cards section and added these three lines above since I guess they do not belong to the real flip-card section?

2020-09-21 14:11 UTC, Gabbi-89 commented on code/style.css
> +    }
You mix between RGB, HEX and colorname when coloring the parts. Maybe you can choose one of those three and stick to it? I think that would be easier if you shall code together with some other.

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +        nickname: 'mrGreen',
Cool that you sort the objects in an array directly! 👍🏼

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +        favouriteWeapon: 'knife'
You haven't used the favouriteWeapons on the webpage so maybe they are not needed right now?

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +];
Maybe you can comment this out until you will be using favouriteWeapons?

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +// Randomly selects an item from the array you pass into the function
Same as above comment - comment it out for now?

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +    // Randomly selects a favouriteWeapon from the favouriteWeapons-array and adds that to the mystery object.
Change this comment since you are picking a weapon for the weapon card but you are not using favouriteWeapons for the suspects.

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
>  }
Easy and nice to follow! And the namings does really make sense! :) 💯

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +}
Really liked this part and that you got it to work! 💯

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +    }
COOL! 
I was just thinking about why the killer/weapon/room changes before the cards flip. But maybe that is related to where in the JS file you put this function. Now it for eg. picks a killer and then flips the card. Is there any way yo change that?

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +let suspects = [{
Change from 'let' to 'const' since these are not changing. :)

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +const weapons = [{
Here you use const - nice! 👍🏼

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +let weaponArray = [
Possible to change from 'let' to 'const'?

2020-09-21 14:11 UTC, Gabbi-89 commented on code/clue.js
> +const pickRoom = () => {
Correctly written functions 💯

2020-10-05 07:41 UTC, EmOlsz requested changes
Good job Sara! In general, your JS flow is well done, logic works and operations on arrays are working :) There are some things that needs to be fixed, mostly small stuff though.
Take a look on both Gabriela's and my comments and provide changes, only after that I will be able to approve your pull request

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +let suspects = [{
Good point Gabriela!

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +let weaponArray = [
Yep, needs to be `const`

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +const shufflefavouriteWeapons = (arrayOfSuspects) => {
No need for parentheses if we provide only one argument

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +        suspect.weapon = weaponArray[Math.floor(Math.random() * 9)];
`9` should be replaced by `weaponArray.length`

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +    weapon: '',
It's even more semantic approach to initialise mystery object with `null` values like this :

```
const mystery = {
  killer: null,
  room: null,
  weapon: null
}
```

Moreover, you can use `const` keyword - we will be changing values of properties, that's true, but JavaScript will not consider this as overwriting. What counts for JavaScript is that object will stay object

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +    document.getElementById('killerCard').style.background = mystery.killer.color;
You are adding `background` too high in HTML structure - because of that entire card is covered on given color and we cannot see image, description etc. Needs to be fixed

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +    The murder can 't be resolved yet.`;
Wrong indentation

2020-10-05 07:41 UTC, EmOlsz commented on code/clue.js
> +    if (mystery.killer == "" || mystery.favouriteWeapon == "" || mystery.room == "") {
We should almost always use `===` instead of `==`. The first one will check both value and type, second one will check only value. It's curial difference, take a look :

1. `12 == "12"` will be true
2. `12 === "12"` will be false

2020-10-05 07:41 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="./style.css" />
Great, `./` in path :)

2020-10-05 07:41 UTC, EmOlsz commented on code/index.html
> +        <Section class="message">
Uppercase HTML tag - this needs to be fixed

2020-10-05 07:41 UTC, EmOlsz commented on code/style.css
> +    body {
Wrong indentation in whole file

2020-10-15 15:04 UTC, EmOlsz approved these changes

2021-03-11 09:10 UTC, closed without merging