Bam Week 5: Cluedo card generator
Technigo/project-cluedo pull request #140
Opened 2020-09-20 19:10 UTC by BamStugendal

The first steps were relatively easy but for a more advanced level, I had a harder time wrapping my head around. Like how the logic and what I needed to do to make the functions. If I had more time I would like to write the code so it isn’t so buggy. Because right now you have to click the card in the right order for it to work and so on. 

**Live link**: https://cluedo-generator.netlify.app/code/

2020-09-21 15:14 UTC, JHarde approved these changes

2020-09-21 15:14 UTC, JHarde commented on code/clue.js
Good and clear display of the objects, well done! 👍

2020-09-21 15:14 UTC, JHarde commented on code/clue.js
> +const revealValdidation = () => {
Nice feature adding the validation so you have to pick all three cards to move on to the next page! 😃

2020-09-21 15:14 UTC, JHarde commented on code/clue.js
> +const resetCards = () => {
Well done with the reset button! 👍

2020-09-21 15:14 UTC, JHarde commented on code/clue.js
> +const shuffleWeapon = (arrayOfSuspects) => {
Nice job with the shuffling functions! Was there supposed to be a button in which the user could manually change the favourite weapon? 🤔

2020-09-21 15:14 UTC, JHarde commented on code/style.css
> +.lds-ring div {
Supercool loading function! 🥇

2020-09-21 15:14 UTC, JHarde commented on code/style.css
> +
Cool hover feature!

2020-09-21 15:14 UTC, JHarde commented on code/style.css
>  }
Nice with different colors on the decks, makes it easy to spot the difference between them :)

2020-09-21 15:14 UTC, JHarde commented on code/index.html
> +    </section>
I like that you wrapped the h1 in a section!

2020-09-21 15:14 UTC, JHarde commented on code/index.html
> +          <div></div>
What are the empty divs used for? 🤔

2020-09-21 15:14 UTC, JHarde commented on code/index.html
> +        <h2>KILLER</h2>
Like how you changed "killer" from <p> tag to <h2>

2020-09-21 15:17 UTC, JHarde approved these changes
Really nice design of the page, makes me want to play Cluedo more often! Like how clear the code is, makes total sense! Can see that you aimed high and you definitely did a great job! Only thing I'm missing is a button for changing the favourite weapon so that it gets displayed for the user. Yet again, great job, be proud of yourself! 🏅

2020-10-06 07:03 UTC, EmOlsz requested changes
Congratulations, great job! A lot of extra requirements done :) I'm happy to see such advanced code.
Still, there is couple of things you could fix / improve - please, take a look on my comments :) After that, I'll be able to approve your project

2020-10-06 07:03 UTC, EmOlsz commented on code/clue.js
> +  weapon: null,
Very nice initialisation of object, it's the most semantic way to use `null` values :)

Moreover, you can use `const` keyword over here - we will be changing values of properties, that's true, but JavaScript will not consider this as overwriting. What counts for JavaScript is that object will stay object

2020-10-06 07:03 UTC, EmOlsz commented on code/clue.js
> +}
We can simplify that :

```
const favoriteWeapon = suspect => weapons.find(weapon => weapon.id === suspect.favouriteWeapon);
```

2020-10-06 07:03 UTC, EmOlsz commented on code/clue.js
> +  if (mystery.killer === null || mystery.weapon === null || mystery.room === null) {
We can simplify that :

```
if (!mystery.killer || ... ) { ... }
```

For further reference check out https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/

2020-10-06 07:03 UTC, EmOlsz commented on code/index.html
>      <link rel="stylesheet" href="style.css" />
Let's not forget about `./` in path to file

2020-10-06 07:03 UTC, EmOlsz commented on code/style.css
> +  margin-bottom:  -100px;
It's not the best idea to use margin with values lower than zero. Aren't there better options?

2020-10-06 07:03 UTC, EmOlsz commented on code/style.css
> +
Unnecessary blank line

2020-10-06 07:03 UTC, EmOlsz commented on code/style.css
> +  animation-delay: -0.45s;
Good job :)

2021-01-11 08:18 UTC, EmOlsz approved these changes

2021-03-11 09:11 UTC, closed without merging