Project 5 - Petra Almgren
Technigo/project-cluedo pull request #141
Opened 2020-09-20 20:05 UTC by petrame

I did the red and black level. This week I struggled with undefined, I find it difficult to send arrays and object between different functions. I spent a lot of time console logging.

Two things that didn't work out the way I wanted:
1. I couldn't get the type function to work with aruments,  maybe because it invokes itself? It's therefore inside the revealMystery function.
2. The animated text doesn't work very well when clicking the button several times before type() is done writing. It then starts to print gibberish.

2020-09-21 19:32 UTC, karinnordkvist approved these changes
Petra! I truly enjoyed reading your code. Not only did I learn a lot of new things, I also got a chance to see functions similar to my own written in a much more elegant way than mine. Your JS is logical, smart and all in all easy to understand. I'm very impressed with how you applied the fillArray-function to all favorite-situations and one toggle-function for all three decks' front- and backside. I'll try to remember those pieces of code- for sure!

There are however a few places where you added styling with JS. Try to avoid that and instead create classes with few properties and add with JS. 

Loved all of the extra css/style-bling, from animations to typewriter-function. The loading-animation is also really pretty and that code was cool to see! 

GREAT job!

2020-09-21 19:32 UTC, karinnordkvist commented on README.md
> +This week's motto: More is more!
Love that 😍

2020-09-21 19:32 UTC, karinnordkvist commented on code/index.html
> +    <h1>CLUEDO</h1>
Maybe put the h1-tag in a header-tag? Or add a comment above just to clarify that the h1 belongs to the header?

2020-09-21 19:32 UTC, karinnordkvist commented on code/index.html
> +      <article class="deck killer-deck" id="killerCard" onclick="pickKiller()">
Nice CSS-structure here with the general deck-class. 👌

2020-09-21 19:32 UTC, karinnordkvist commented on code/index.html
> +          <img id="killerImage" class="killer-image" src="" height="150" />
Don't forget to add px to the height-value. (And consider moving it to the css-file 😊)

2020-09-21 19:32 UTC, karinnordkvist commented on code/index.html
> +      <button id="revealButton" class="" onclick="revealMystery()">Reveal the crime</button>
Do you need this empty class here?

2020-09-21 19:32 UTC, karinnordkvist commented on code/index.html
> +            <span></span>
_tiiiiiiiny_ comment- in your footer you create a class called footer (which is great). Maybe add a class here as well, just to make the code a bit more clear?

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +  margin: 30px 0 40px 0;
In mine and Gabriella's pizzabot-project @EmOlsz told us to write the margins like this when you have two of the same value. Ie if the left and right value is the same, you can type it once and it'll still work. 

`margin: 30px 0 40px;`

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +  animation: shake 0.16s infinite alternate;
Cool! 🤩

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +  margin: 20px 0 5px 0;
Same comment as for row 8.

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +p,
I've been told not to style using the semantic tags, but to add classes to them. A p-tag might be more frequently used, which means that this p-style could get problematic.. 🤷‍♀️

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +img {
Same as for above. 😊

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +  transform: translate3d(0);
OK, absolutely starstruck here. 🤩

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +  transition: opacity 0.5s ease-in;
Cool that you managed to fix a transition even though using display:none. 👌👌

2020-09-21 19:32 UTC, karinnordkvist commented on code/style.css
> +  transform: translateY(1px);
Cool!

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +  color: "darkseagreen",
Smart to use html-names for colors! 🌟

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +  room: "",
There's an extra comma at the end here

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +const fillArray = (item, amountOfTimes) => {
Elegant! (Much more elegant than mine 🙈)

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +      ...fillArray(mystery.killer.favouriteWeapon, 5),
Again, super elegant!! 🌟🌟🌟🌟

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +    const onlyFavouriteRooms = fillArray(mystery.weapon, 8);
OH, mind officially blown. Super-smart to make that favorite/relevance-function to be applicable to all decks. Seriously impressed!

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +const shuffleFavouriteWeapon = (array) => {
Since this function is the same as the randomSelector-function, you should be able to use that function for this too?

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +const toggleActive = (front, back) => {
Cool that you use the toggle-function for this. It makes it feel like you actually draw a new (randomized) card! 😊👌

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +  setTimeout(() => (front.style.opacity = 1), 50);
Maks told me to never add styling preferences in the js-file. A way around it is to create a class and to use classList-add/remove instead. 😊😊

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +    toggleActive(killerDeckFront, killerDeckBack);
Once again, elegant! 💎

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +  // If mystery already is reveald once - the button have a 'Start over' function
Smart!!

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +    toggleActive(
Nice way to hide all with that toggle-function!

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +      }, in the ${mystery.room.toLowerCase()} with a ${mystery.weapon.name.toLowerCase()}.`;
Indentation lookin a bit funky here! 🙃🙃

2020-09-21 19:32 UTC, karinnordkvist commented on code/clue.js
> +    // Type text animation
Supernice bonus-feature! 😍

2020-10-06 07:58 UTC, EmOlsz requested changes
Great project Petra! I'm impressed, both by technical and visual aspects of your achievement :) You've done tremendous job this week with extra requirements.
I've added some comments which I hope will help you improve. Provide those small changes into your code and then I will be able to approve your project

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +    "A former psychiatrist who lost his medical license for having an affair with a patient.",
No need for line break here

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +  room: "",
Actually, extra comma on last property is considered good practice - thanks to that, we can later on add new property to initialised object without worrying about syntaxError.

It's even more semantic approach to initialise mystery object with `null` values like this :

```
const mystery = {
  killer: null,
  room: null,
  weapon: null
}
```

Moreover, you can use `const` keyword - we will be changing values of properties, that's true, but JavaScript will not consider this as overwriting. What counts for JavaScript is that object will stay object

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +const favouriteWeaponArray = (weapons) => {
If we pass one argument, we can omit parentheses :

`const favouriteWeaponArray = weapons => { ... }`

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +  if (mystery.killer.favouriteWeapon) {
Great job with how you write your statements!
For further reference, check out https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +    const newRoomArray = [...rooms];
It's very good you've done it. I'm just wondering if you fully understand what is happening here

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +      index++;
No need to add `index++` over here, it doesn't do anything

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +  mysteryReveald.innerHTML = "Who did it?";
It's only text you are passing, so instead of `.innerHTML` you should use `innerText`

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +    mystery.killer = "";
`mystery.killer = null` would be far better

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +    mystery.room = "";
```
mystery.killer = null;
mystery.weapon = null;
mystery.room = null;
```

2020-10-06 07:58 UTC, EmOlsz commented on code/clue.js
> +      }, in the ${mystery.room.toLowerCase()} with a ${mystery.weapon.name.toLowerCase()}.`;
Yep, needs to be fixed :p

2020-10-06 07:58 UTC, EmOlsz commented on code/index.html
>      <link rel="stylesheet" href="style.css" />
`./` missing in path to file

2020-10-13 08:56 UTC, EmOlsz approved these changes

2021-03-11 09:11 UTC, closed without merging