Project 5: Cluedo, Michel Elmoznino Laufer
Technigo/project-cluedo pull request #16
Opened 2019-10-27 09:25 UTC by MichelLaufer

Fun project!

2019-10-29 19:08 UTC, ericaglimsholt requested changes
Please add your Netlify link to the PR!

2019-10-29 19:54 UTC, MichelLaufer commented
Hi!

I added the Netlify-link in Canvas, and it is:
https://michel-cluedo.netlify.com

Best,
Michel
________________________________
From: Erica Glimsholt <notifications@github.com>
Sent: Tuesday, October 29, 2019 7:08:54 PM
To: Technigo/project-cluedo <project-cluedo@noreply.github.com>
Cc: Michel Elmoznino Laufer <mitchel_85@hotmail.com>; Author <author@noreply.github.com>
Subject: Re: [Technigo/project-cluedo] Project 5: Cluedo, Michel Elmoznino Laufer (#16)


@ericaglimsholt requested changes on this pull request.

Please add your Netlify link to the PR!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechnigo%2Fproject-cluedo%2Fpull%2F16%3Femail_source%3Dnotifications%26email_token%3DAMBTWB5LVKH6J2VIAIIIXKLQRCC4NA5CNFSM4JFQ4AE2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCJTWJ2Y%23pullrequestreview-308765931&data=02%7C01%7C%7Ca58dd92e4a4943492fdf08d75ca3712b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637079729352001307&sdata=yWD%2FTEakiML%2F2DmBYnObVNjwVZNBTuMe19vXmRFiX1s%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMBTWBZDNWTCZ36RIPOLRZTQRCC4NANCNFSM4JFQ4AEQ&data=02%7C01%7C%7Ca58dd92e4a4943492fdf08d75ca3712b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637079729352011312&sdata=o%2FbHYXJ7DfWQUOXya%2BNWKvpd6jCX68e4XaXq0zs6%2F3o%3D&reserved=0>.

2019-10-31 08:34 UTC, ericaglimsholt approved these changes
Great work! 🚀 What you can think about is how to make the code less. That's something you always should aim for - less code makes it easier to read and won't take up so much space (because code weights)

2019-10-31 08:34 UTC, ericaglimsholt commented on code/clue.js
> +const livingroom = "Living Room";
If you are only  this as simple strings you can add it directly to your `rooms` variable. This means less code, which you always should aim for. Ex: 
```
const rooms = [
  "Dinning Room",
  "Conservatory",
];
```

2019-10-31 08:34 UTC, ericaglimsholt commented on code/clue.js
> +]
Same goes here as above

2020-09-14 07:41 UTC, closed without merging