Project-5 Anna Almestål
Technigo/project-cluedo pull request #29
Opened 2019-10-27 20:51 UTC by anna-ip

This week have been really hard, until mid-day Thursday I had no clue of what I was doing, Thursday noon I met up with some of my class-mates and with some help I managed to get it all together by the end of the day and I think I do understand some of what I've done this week. 

Netlify link [https://cluedo-annaalmestal.netlify.com/](url)

2019-10-31 09:18 UTC, ericaglimsholt requested changes
Hi Anna, your Netlify link doesn't work. Can you take a look at it and add a working one here?

2019-10-31 09:39 UTC, anna-ip commented
Hej Erica

Här kommer den https://cluedo-annaalmestal.netlify.com <https://cluedo-annaalmestal.netlify.com/>

//Anna

> 31 okt. 2019 kl. 10:18 skrev Erica Glimsholt <notifications@github.com>:
> 
> @ericaglimsholt requested changes on this pull request.
> 
> Hi Anna, your Netlify link doesn't work. Can you take a look at it and add a working one here?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Technigo/project-cluedo/pull/29?email_source=notifications&email_token=AMMFQGUEAKPXXUIFJZEJ2DDQRKPGLA5CNFSM4JFTLU3KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCJ3C5ZA#pullrequestreview-309735140>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AMMFQGTDSGF4TG6NE5GMHKDQRKPGLANCNFSM4JFTLU3A>.
>

2019-11-03 11:52 UTC, ericaglimsholt approved these changes
Good work on your project! One thing to think about is to make to code more easier to read. Comments helps, but there's a lot of out commented code (like functions) that doesn't need to be there at all. It's a good thing to start working on readable code even now in the start. That's something people look like when they're hiring a new developer! Good luck!

2019-11-03 11:52 UTC, ericaglimsholt commented on code/clue.js
> +  description: "She....",
Interesting descriptions of the persons!

2020-02-03 16:29 UTC, closed without merging