Projecct 5 - Cluedo
Technigo/project-cluedo pull request #33
Opened 2019-10-28 14:30 UTC by Jenfi

I was struggling a lot with the javascript. 

I also found that the instructions were quite difficult to understand, which made it even a bit more tricky. 

I decided not to make the site responsive for now, just to save time.

2019-10-31 09:52 UTC, ericaglimsholt requested changes
Hi! Can you add the Netlify link to your PR?

2019-10-31 12:04 UTC, Jenfi commented
> Hi! Can you add the Netlify link to your PR?

Hi Erica,

I linked the wrong Netlify by mistake, pls note correct link:
https://jenniferfick-cluedo-project.netlify.com/

2019-11-03 11:59 UTC, ericaglimsholt approved these changes
Nice work on the Cluedo project! Seems like you manage Javascript pretty well! Looking forward to see the next project

2019-11-03 11:59 UTC, ericaglimsholt commented on code/style.css
> +  background: url("questionmark.png") center no-repeat;
This is so cleaver! It looks really nice

2019-11-03 11:59 UTC, ericaglimsholt commented on code/clue.js
> +  image: "scarlett.png",
How come the image for missScarlet isn't in the assets folder like the other ones?

2019-11-03 11:59 UTC, ericaglimsholt commented on code/style.css
> +font-size: 50px;
Indent

2019-11-03 11:59 UTC, ericaglimsholt commented on code/style.css
> +    padding: 7px;
Unindent

2019-11-03 11:59 UTC, ericaglimsholt commented on code/style.css
> +  }
Unindent

2020-02-03 16:29 UTC, closed without merging