Project Cluedo
Technigo/project-cluedo pull request #35
Opened 2019-10-28 19:50 UTC by JoacimNilsen

I used the already made layout and tweaked it a bit in ways of styling, adding background image and some hover effects.
It was fun to start using JS for real and I am happy with the result. I finally understand how it works and now i just want to learn to actually write JS with the same confidant as with CSS and HTML.

2019-10-31 11:31 UTC, ericaglimsholt requested changes
Please add the Netlify link to the PR :)

2019-11-01 14:30 UTC, JoacimNilsen commented
> Please add the Netlify link to the PR :)

I added it to the readme if that is what you meant? 😬

2019-11-03 12:16 UTC, ericaglimsholt approved these changes
Nice submission! When you run the project you get an error in your console. The project still works, but we don't want errors on the page, so please make sure the projects doesn't include errors next time :)

2019-11-03 12:16 UTC, ericaglimsholt commented on code/clue.js
> +document.getElementById("mystery").addEventListener("click");
You get this error when running the project: `Uncaught TypeError: Failed to execute 'addEventListener' on 'EventTarget': 2 arguments required, but only 1 present.`

In this case, this row of code isn't needed what I can see. What was suppost to happen here?

2020-02-03 16:29 UTC, closed without merging