Cluedo
Technigo/project-cluedo pull request #7
Opened 2019-10-25 08:44 UTC by EmmaBerglund1977

2019-10-29 14:49 UTC, ericaglimsholt requested changes
Hi Emma! Can you include your Netlify link in the PR description?

2019-10-30 07:37 UTC, EmmaBerglund1977 commented
https://fervent-davinci-548aa4.netlify.com/

2019-10-31 08:48 UTC, ericaglimsholt approved these changes
Great work! Added some comments for you to think about :)

2019-10-31 08:48 UTC, ericaglimsholt commented on code/clue.js
> +}
When pushing the button (running this function) without clicking on the cards you get back `The murder was committed by undefined undefined, in the [object HTMLDivElement] with a undefined` as a string. And that's maybe not the best. What you can to is to check if `mystery.killer.firstName`, `mystery.killer.lastName`, `mystery.room` and `mystery.weapon.name` has any value. If they do - output the string. If they don't do nothing or add an error message for the user

2019-10-31 08:48 UTC, ericaglimsholt commented on code/clue.js
> +  name: ' knife',
```suggestion
  name: 'knife',
```

2019-10-31 08:48 UTC, ericaglimsholt commented on code/clue.js
> +const patio = 'Patio'
Because you only have this as simple strings, you can add it directly to your array instead of declaring every room as it's own property

2019-10-31 08:48 UTC, ericaglimsholt commented on code/clue.js
> +  //
Empty comment? :)

2020-09-14 07:43 UTC, closed without merging